# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\workspace_py\radar\dialog_para_platform.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_para_platform(object):
    def setupUi(self, Dialog_para_platform):
        Dialog_para_platform.setObjectName("Dialog_para_platform")
        Dialog_para_platform.resize(330, 345)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_para_platform)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog_para_platform)
        self.widget.setStyleSheet("QWidget#widget{background-image:url(:/img/image_dialog.jpg)}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem)
        self.label_56 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("QLabel#label_46{color:white}")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_30.addWidget(self.label_56)
        self.timeEdit = QtWidgets.QTimeEdit(self.widget)
        self.timeEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeEdit.setFont(font)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_30.addWidget(self.timeEdit)
        self.label_57 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("QLabel#label_47{color:white}")
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_30.addWidget(self.label_57)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem2)
        self.label_50 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("QLabel#label_46{color:white}")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_27.addWidget(self.label_50)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setReadOnly(False)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_27.addWidget(self.lineEdit_24)
        self.label_51 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("QLabel#label_47{color:white}")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_27.addWidget(self.label_51)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem4)
        self.label_54 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("QLabel#label_46{color:white}")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_29.addWidget(self.label_54)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setReadOnly(False)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_29.addWidget(self.lineEdit_26)
        self.label_55 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("QLabel#label_47{color:white}")
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_29.addWidget(self.label_55)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem6)
        self.label_52 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("QLabel#label_46{color:white}")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_28.addWidget(self.label_52)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setReadOnly(False)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_28.addWidget(self.lineEdit_25)
        self.label_53 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("QLabel#label_47{color:white}")
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_28.addWidget(self.label_53)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem8)
        self.label_62 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("QLabel#label_46{color:white}")
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_33.addWidget(self.label_62)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_30.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setReadOnly(False)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_33.addWidget(self.lineEdit_30)
        self.label_63 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("QLabel#label_47{color:white}")
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_33.addWidget(self.label_63)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem10)
        self.label_60 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("QLabel#label_46{color:white}")
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_32.addWidget(self.label_60)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_29.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setReadOnly(False)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.horizontalLayout_32.addWidget(self.lineEdit_29)
        self.label_61 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("QLabel#label_47{color:white}")
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_32.addWidget(self.label_61)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem12)
        self.label_58 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("QLabel#label_46{color:white}")
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_31.addWidget(self.label_58)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setReadOnly(False)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.horizontalLayout_31.addWidget(self.lineEdit_28)
        self.label_59 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("QLabel#label_47{color:white}")
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_31.addWidget(self.label_59)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_para_platform)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_para_platform)
        self.buttonBox.accepted.connect(Dialog_para_platform.accept)
        self.buttonBox.rejected.connect(Dialog_para_platform.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_para_platform)

    def retranslateUi(self, Dialog_para_platform):
        _translate = QtCore.QCoreApplication.translate
        Dialog_para_platform.setWindowTitle(_translate("Dialog_para_platform", "平台导航定位信息"))
        self.label_56.setText(_translate("Dialog_para_platform", " 时间"))
        self.timeEdit.setDisplayFormat(_translate("Dialog_para_platform", "hh:mm:ss"))
        self.label_50.setText(_translate("Dialog_para_platform", "  经度"))
        self.label_51.setText(_translate("Dialog_para_platform", "°"))
        self.label_54.setText(_translate("Dialog_para_platform", "  纬度"))
        self.label_55.setText(_translate("Dialog_para_platform", "°"))
        self.label_52.setText(_translate("Dialog_para_platform", " 高度"))
        self.label_53.setText(_translate("Dialog_para_platform", "m"))
        self.label_62.setText(_translate("Dialog_para_platform", "天向速度"))
        self.label_63.setText(_translate("Dialog_para_platform", "m/s"))
        self.label_60.setText(_translate("Dialog_para_platform", "北向速度"))
        self.label_61.setText(_translate("Dialog_para_platform", "m/s"))
        self.label_58.setText(_translate("Dialog_para_platform", "东向速度"))
        self.label_59.setText(_translate("Dialog_para_platform", "m/s"))


import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_para_platform = QtWidgets.QDialog()
    ui = Ui_Dialog_para_platform()
    ui.setupUi(Dialog_para_platform)
    Dialog_para_platform.show()
    sys.exit(app.exec_())
