# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\workspace_py\radar\dialog_para_radar.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_para_radar(object):
    def setupUi(self, Dialog_para_radar):
        Dialog_para_radar.setObjectName("Dialog_para_radar")
        Dialog_para_radar.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_para_radar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog_para_radar)
        self.widget.setStyleSheet("QWidget#widget{background-image:url(:/img/image_dialog.jpg)}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_50 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("QLabel#label_46{color:white}")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_27.addWidget(self.label_50)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setReadOnly(False)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_27.addWidget(self.lineEdit_24)
        self.label_51 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("QLabel#label_47{color:white}")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_27.addWidget(self.label_51)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_48 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("QLabel#label_46{color:white}")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_26.addWidget(self.label_48)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_26.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_52 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("QLabel#label_46{color:white}")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_28.addWidget(self.label_52)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setReadOnly(False)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_28.addWidget(self.lineEdit_25)
        self.label_53 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("QLabel#label_47{color:white}")
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_28.addWidget(self.label_53)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_para_radar)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_para_radar)
        self.buttonBox.accepted.connect(Dialog_para_radar.accept)
        self.buttonBox.rejected.connect(Dialog_para_radar.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_para_radar)

    def retranslateUi(self, Dialog_para_radar):
        _translate = QtCore.QCoreApplication.translate
        Dialog_para_radar.setWindowTitle(_translate("Dialog_para_radar", "雷达模拟器参数"))
        self.label_50.setText(_translate("Dialog_para_radar", "    载波频率"))
        self.label_51.setText(_translate("Dialog_para_radar", "GHz"))
        self.label_48.setText(_translate("Dialog_para_radar", "    极化方式"))
        self.comboBox.setItemText(0, _translate("Dialog_para_radar", "垂直极化"))
        self.comboBox.setItemText(1, _translate("Dialog_para_radar", "水平极化"))
        self.label_52.setText(_translate("Dialog_para_radar", "    入射角度"))
        self.label_53.setText(_translate("Dialog_para_radar", "°"))


import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_para_radar = QtWidgets.QDialog()
    ui = Ui_Dialog_para_radar()
    ui.setupUi(Dialog_para_radar)
    Dialog_para_radar.show()
    sys.exit(app.exec_())
