# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\workspace_py\radar\dialog_para_env.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_para_env(object):
    def setupUi(self, Dialog_para_env):
        Dialog_para_env.setObjectName("Dialog_para_env")
        Dialog_para_env.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_para_env)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog_para_env)
        self.widget.setStyleSheet("QWidget#widget{background-image:url(:/img/image_dialog.jpg)}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem)
        self.label_50 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("QLabel#label_46{color:white}")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_27.addWidget(self.label_50)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setReadOnly(False)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_27.addWidget(self.lineEdit_24)
        self.label_51 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("QLabel#label_47{color:white}")
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_27.addWidget(self.label_51)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem2)
        self.label_52 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("QLabel#label_46{color:white}")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_28.addWidget(self.label_52)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setReadOnly(False)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_28.addWidget(self.lineEdit_25)
        self.label_53 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("QLabel#label_47{color:white}")
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_28.addWidget(self.label_53)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem4)
        self.label_54 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("QLabel#label_46{color:white}")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_29.addWidget(self.label_54)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setReadOnly(False)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_29.addWidget(self.lineEdit_26)
        self.label_55 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("QLabel#label_47{color:white}")
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_29.addWidget(self.label_55)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog_para_env)
        self.buttonBox.accepted.connect(Dialog_para_env.accept)
        self.buttonBox.rejected.connect(Dialog_para_env.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_para_env)

    def retranslateUi(self, Dialog_para_env):
        _translate = QtCore.QCoreApplication.translate
        Dialog_para_env.setWindowTitle(_translate("Dialog_para_env", "海洋环境参数"))
        self.label_50.setText(_translate("Dialog_para_env", "风级"))
        self.label_52.setText(_translate("Dialog_para_env", "浪高"))
        self.label_53.setText(_translate("Dialog_para_env", "m"))
        self.label_54.setText(_translate("Dialog_para_env", "风区"))


import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_para_env = QtWidgets.QDialog()
    ui = Ui_Dialog_para_env()
    ui.setupUi(Dialog_para_env)
    Dialog_para_env.show()
    sys.exit(app.exec_())
