# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\workspace_py\radar\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 614)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralWidget.setStyleSheet("QWidget#centralWidget{background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.994, stop:0 rgba(242, 238, 255, 8), stop:1 rgba(47, 173, 218, 96))}")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QWidget#tabWidget{background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.994, stop:0 rgba(242, 238, 255, 8), stop:1 rgba(47, 173, 218, 96))}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("QWidget#tab{background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.994, stop:0 rgba(242, 238, 255, 8), stop:1 rgba(47, 173, 218, 96))}")
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QtCore.QSize(9999, 150))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_13 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.widget_13.setFont(font)
        self.widget_13.setStyleSheet("QWidget#widget_13{border: 1px solid gray}")
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_13)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_2.addWidget(self.radioButton_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_13)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.widget_13)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_13)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 5, 1, 1, 1)
        self.horizontalLayout.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.widget_14.setFont(font)
        self.widget_14.setStyleSheet("QWidget#widget_14{border: 1px solid gray}")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_8.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_8.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_8.addWidget(self.radioButton_6)
        self.horizontalLayout.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setStyleSheet("QWidget#widget_15{border: 1px solid gray}")
        self.widget_15.setObjectName("widget_15")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setStyleSheet("QWidget#widget_16{border: 1px solid gray}")
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.widget_16)
        self.widget_18 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton = QtWidgets.QPushButton(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_13.addWidget(self.pushButton)
        self.radioButton_7 = QtWidgets.QRadioButton(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_13.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_13.addWidget(self.radioButton_8)
        self.radioButton_11 = QtWidgets.QRadioButton(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_13.addWidget(self.radioButton_11)
        self.horizontalLayout.addWidget(self.widget_18)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_5 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_5.sizePolicy().hasHeightForWidth())
        self.page_5.setSizePolicy(sizePolicy)
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_5.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_1 = QtWidgets.QWidget(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_1.sizePolicy().hasHeightForWidth())
        self.widget_1.setSizePolicy(sizePolicy)
        self.widget_1.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_1.setObjectName("widget_1")
        self.verticalLayout.addWidget(self.widget_1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_6 = QtWidgets.QWidget(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_6.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_2 = QtWidgets.QWidget(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4.addWidget(self.widget_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_4 = QtWidgets.QWidget(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(220, 0))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6.addWidget(self.widget_4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_5)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_7.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_8.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5.addWidget(self.widget_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_9 = QtWidgets.QWidget(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(220, 0))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_8.addWidget(self.widget_9)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_7)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_10 = QtWidgets.QWidget(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_10.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_6.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_11.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_6.addWidget(self.widget_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_12 = QtWidgets.QWidget(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMinimumSize(QtCore.QSize(220, 0))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_10.addWidget(self.widget_12)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_9)
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_24 = QtWidgets.QWidget(self.page_2)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_18.addWidget(self.widget_24)
        self.horizontalLayout_21.addLayout(self.verticalLayout_18)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_8.setMaximumSize(QtCore.QSize(81, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_21.addWidget(self.pushButton_8)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.widget_19 = QtWidgets.QWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setMinimumSize(QtCore.QSize(750, 400))
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_36.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem)
        self.radioButton_9 = QtWidgets.QRadioButton(self.widget_20)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.radioButton_9.setFont(font)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_14.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.widget_20)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(7)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_14.addWidget(self.radioButton_10)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton.sizePolicy().hasHeightForWidth())
        self.commandLinkButton.setSizePolicy(sizePolicy)
        self.commandLinkButton.setMaximumSize(QtCore.QSize(100, 40))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout_14.addWidget(self.commandLinkButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.horizontalLayout_36.addWidget(self.widget_20)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_36)
        self.stackedWidget_2.addWidget(self.page)
        self.verticalLayout_7.addWidget(self.stackedWidget_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("QWidget#teb_2{background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.994, stop:0 rgba(242, 238, 255, 8), stop:1 rgba(47, 173, 218, 96))}")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_17 = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.widget_17.setFont(font)
        self.widget_17.setStyleSheet("QWidget#widget_17{background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.994, stop:0 rgba(242, 238, 255, 8), stop:1 rgba(47, 173, 218, 96))}")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.widget_22 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setStyleSheet("QWidget#widget_22{border: 1px solid gray}")
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.label_53 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_9.addWidget(self.label_53)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget_22)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_18.addWidget(self.lineEdit_10)
        self.label_19 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_19.setFont(font)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_22)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_17.addWidget(self.lineEdit_9)
        self.label_17 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_22)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_16.addWidget(self.lineEdit_8)
        self.label_15 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_15.setFont(font)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        self.verticalLayout_16.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addWidget(self.widget_22)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.widget_21 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_21.sizePolicy().hasHeightForWidth())
        self.widget_21.setSizePolicy(sizePolicy)
        self.widget_21.setStyleSheet("QWidget#widget_21{border: 1px solid gray}")
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem14)
        self.label_4 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_21)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_14.addWidget(self.lineEdit_3)
        self.label_12 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem16)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_23 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_20.addWidget(self.label_23)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_20.addWidget(self.lineEdit_11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem17)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_21)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_15.addWidget(self.lineEdit_6)
        self.label_20 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_21 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_19.addWidget(self.label_21)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_21)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_19.addWidget(self.lineEdit_7)
        self.label_22 = QtWidgets.QLabel(self.widget_21)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.verticalLayout_15.addLayout(self.verticalLayout_10)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem19)
        self.horizontalLayout_2.addWidget(self.widget_21)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem20)
        self.widget_23 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_23.sizePolicy().hasHeightForWidth())
        self.widget_23.setSizePolicy(sizePolicy)
        self.widget_23.setStyleSheet("QWidget#widget_23{border: 1px solid gray}")
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem21)
        self.label_57 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_11.addWidget(self.label_57)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem22)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_46 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_25.addWidget(self.label_46)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.widget_23)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_25.addWidget(self.lineEdit_22)
        self.label_47 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_25.addWidget(self.label_47)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem23)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_41 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_22.addWidget(self.label_41)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget_23)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_22.addWidget(self.lineEdit_20)
        self.label_42 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_22.addWidget(self.label_42)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem24)
        self.verticalLayout_11.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_55 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_33.addWidget(self.label_55)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.widget_23)
        self.lineEdit_27.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.horizontalLayout_33.addWidget(self.lineEdit_27)
        self.label_56 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_33.addWidget(self.label_56)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem25)
        self.verticalLayout_11.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_43 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_23.addWidget(self.label_43)
        self.comboBox = QtWidgets.QComboBox(self.widget_23)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_23.addWidget(self.comboBox)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem26)
        self.verticalLayout_11.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_51 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_29.addWidget(self.label_51)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.horizontalLayout_29.addWidget(self.comboBox_2)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem27)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_48 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_26.addWidget(self.label_48)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.widget_23)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_26.addWidget(self.lineEdit_23)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem28)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_52 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_30.addWidget(self.label_52)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget_23)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_30.addWidget(self.lineEdit_26)
        self.label_45 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_30.addWidget(self.label_45)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem29)
        self.verticalLayout_11.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_44 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_24.addWidget(self.label_44)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.widget_23)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_24.addWidget(self.lineEdit_21)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem30)
        self.verticalLayout_11.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_50 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_28.addWidget(self.label_50)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget_23)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_28.addWidget(self.lineEdit_25)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem31)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_49 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_27.addWidget(self.label_49)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget_23)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_27.addWidget(self.lineEdit_24)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem32)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_54 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_32.addWidget(self.label_54)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.widget_23)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.horizontalLayout_32.addWidget(self.lineEdit_28)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem33)
        self.verticalLayout_11.addLayout(self.horizontalLayout_32)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem34)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem35)
        self.verticalLayout_17.addLayout(self.verticalLayout_11)
        self.horizontalLayout_2.addWidget(self.widget_23)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem36)
        self.widget_21.raise_()
        self.widget_22.raise_()
        self.widget_23.raise_()
        self.verticalLayout_12.addWidget(self.widget_17)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "海杂波模拟器"))
        self.radioButton_3.setText(_translate("MainWindow", "韦布尔分布"))
        self.label_2.setText(_translate("MainWindow", "形状参数(瑞利方差)"))
        self.lineEdit.setText(_translate("MainWindow", "0.6"))
        self.label.setText(_translate("MainWindow", "杂波幅度分布类型"))
        self.radioButton_2.setText(_translate("MainWindow", "瑞利分布"))
        self.radioButton.setText(_translate("MainWindow", "对数正太分布"))
        self.label_3.setText(_translate("MainWindow", "尺度参数"))
        self.lineEdit_2.setText(_translate("MainWindow", "1.5"))
        self.label_6.setText(_translate("MainWindow", "杂波功率谱类型"))
        self.radioButton_4.setText(_translate("MainWindow", "高斯谱"))
        self.radioButton_5.setText(_translate("MainWindow", "平方谱"))
        self.radioButton_6.setText(_translate("MainWindow", "立方谱"))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "SCR"))
        self.label_7.setText(_translate("MainWindow", "信杂比/杂噪比"))
        self.label_8.setText(_translate("MainWindow", "dB"))
        self.label_10.setText(_translate("MainWindow", "dB"))
        self.lineEdit_5.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "CNR"))
        self.pushButton_4.setText(_translate("MainWindow", "MTD处理"))
        self.pushButton_2.setText(_translate("MainWindow", "脉压处理"))
        self.pushButton_3.setText(_translate("MainWindow", "二脉冲MTI"))
        self.pushButton_5.setText(_translate("MainWindow", "三脉冲MTI"))
        self.pushButton_6.setText(_translate("MainWindow", "STFT处理"))
        self.pushButton_7.setText(_translate("MainWindow", "杂波图"))
        self.pushButton.setText(_translate("MainWindow", "运行杂波处理"))
        self.radioButton_7.setText(_translate("MainWindow", "二维图"))
        self.radioButton_8.setText(_translate("MainWindow", "三维图"))
        self.radioButton_11.setText(_translate("MainWindow", "多普勒图"))
        self.pushButton_8.setText(_translate("MainWindow", "计算多普勒图"))
        self.radioButton_9.setText(_translate("MainWindow", "海浪平面"))
        self.radioButton_10.setText(_translate("MainWindow", "后向散射系数"))
        self.commandLinkButton.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "系统模拟"))
        self.label_53.setText(_translate("MainWindow", "平台导航定位信息"))
        self.label_18.setText(_translate("MainWindow", "时间"))
        self.label_16.setText(_translate("MainWindow", "经度"))
        self.label_13.setText(_translate("MainWindow", "纬度"))
        self.label_4.setText(_translate("MainWindow", "海洋运动数据"))
        self.label_11.setText(_translate("MainWindow", "风速"))
        self.label_12.setText(_translate("MainWindow", "m/s"))
        self.label_23.setText(_translate("MainWindow", "风级"))
        self.label_14.setText(_translate("MainWindow", "浪高"))
        self.label_20.setText(_translate("MainWindow", "m"))
        self.label_21.setText(_translate("MainWindow", "风区"))
        self.label_57.setText(_translate("MainWindow", "雷达模拟器参数"))
        self.label_46.setText(_translate("MainWindow", "    载波频率"))
        self.label_47.setText(_translate("MainWindow", "GHz"))
        self.label_41.setText(_translate("MainWindow", "    信号带宽"))
        self.label_42.setText(_translate("MainWindow", "MHz"))
        self.label_55.setText(_translate("MainWindow", "脉冲重复频率"))
        self.label_56.setText(_translate("MainWindow", "MHz"))
        self.label_43.setText(_translate("MainWindow", "    极化方式"))
        self.comboBox.setItemText(0, _translate("MainWindow", "垂直极化"))
        self.comboBox.setItemText(1, _translate("MainWindow", "水平极化"))
        self.label_51.setText(_translate("MainWindow", "    调制方式"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "线性调频脉冲信号"))
        self.label_48.setText(_translate("MainWindow", "      杂噪比"))
        self.label_52.setText(_translate("MainWindow", "    入射角度"))
        self.label_45.setText(_translate("MainWindow", "°"))
        self.label_44.setText(_translate("MainWindow", "    波束宽度"))
        self.label_50.setText(_translate("MainWindow", "    中心角度"))
        self.label_49.setText(_translate("MainWindow", "    形状参数"))
        self.label_54.setText(_translate("MainWindow", "    散射系数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "典型指标"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
