# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\workspace_py\radar\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 555)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow#MainWindow{padding:0px}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralWidget.setStyleSheet("QWidget#centralWidget{margin:0px}")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_17 = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        self.widget_17.setStyleSheet("QWidget#widget_17{background-image: url(:/img/w69rlkBnY3.jpg)}")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(530, 16777215))
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_5 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_5.sizePolicy().hasHeightForWidth())
        self.page_5.setSizePolicy(sizePolicy)
        self.page_5.setObjectName("page_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_5.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_5.setStyleSheet("QWidget#widget_5{border: 1px solid gray}")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout.addWidget(self.widget_5)
        self.widget = QtWidgets.QWidget(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(250, 100))
        self.widget.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setStyleSheet("QWidget#widget {border: 1px solid gray;}")
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.widget_1 = QtWidgets.QWidget(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_1.sizePolicy().hasHeightForWidth())
        self.widget_1.setSizePolicy(sizePolicy)
        self.widget_1.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_1.setStyleSheet("QWidget#widget_1{border: 1px solid gray}")
        self.widget_1.setObjectName("widget_1")
        self.verticalLayout.addWidget(self.widget_1)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_6 = QtWidgets.QWidget(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_6.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_2 = QtWidgets.QWidget(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4.addWidget(self.widget_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_4 = QtWidgets.QWidget(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(220, 0))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6.addWidget(self.widget_4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_5)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_7.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_8.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5.addWidget(self.widget_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_9 = QtWidgets.QWidget(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(220, 0))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_8.addWidget(self.widget_9)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_7)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_10 = QtWidgets.QWidget(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_10.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_6.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_11.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_6.addWidget(self.widget_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_12 = QtWidgets.QWidget(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMinimumSize(QtCore.QSize(220, 0))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_10.addWidget(self.widget_12)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_9)
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_24 = QtWidgets.QWidget(self.page_2)
        self.widget_24.setMaximumSize(QtCore.QSize(510, 250))
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_18.addWidget(self.widget_24)
        self.widget_21 = QtWidgets.QWidget(self.page_2)
        self.widget_21.setMaximumSize(QtCore.QSize(510, 250))
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_18.addWidget(self.widget_21)
        self.horizontalLayout_21.addLayout(self.verticalLayout_18)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setObjectName("page")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.widget_19 = QtWidgets.QWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setMinimumSize(QtCore.QSize(530, 400))
        self.widget_19.setMaximumSize(QtCore.QSize(530, 16777215))
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_36.addWidget(self.widget_19)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_36)
        self.stackedWidget_2.addWidget(self.page)
        self.horizontalLayout.addWidget(self.stackedWidget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QtCore.QSize(9999, 9999))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_20 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setMinimumSize(QtCore.QSize(270, 0))
        self.widget_20.setMaximumSize(QtCore.QSize(270, 300))
        self.widget_20.setStyleSheet("QWidget#widget_20{background-image:url(:/img/5njp9xK6q95.png)}")
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_16 = QtWidgets.QWidget(self.widget_20)
        self.widget_16.setStyleSheet("QWidget#widget_16{border: 1px solid gray;margin-left:5px;margin-right:5px;margin-bottom:5px;margin-top:5px}")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_5 = QtWidgets.QLabel(self.widget_16)
        self.label_5.setMinimumSize(QtCore.QSize(0, 16))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel#label_5{margin-left:5px;margin-right:5px;color:white}")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_20.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel#label_4{color:white}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_16)
        self.lineEdit_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_20.addLayout(self.horizontalLayout_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_16)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5{border:1px solid gray;border-radius: 5px;color:white; }")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_20.addWidget(self.pushButton_5)
        self.line = QtWidgets.QFrame(self.widget_16)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line.setFont(font)
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_20.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel#label{margin-left:5px;margin-right:5px;color:white}")
        self.label.setObjectName("label")
        self.verticalLayout_20.addWidget(self.label)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_46 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("QLabel#label_46{color:white}")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_25.addWidget(self.label_46)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.widget_16)
        self.lineEdit_22.setEnabled(False)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_25.addWidget(self.lineEdit_22)
        self.label_47 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("QLabel#label_47{color:white}")
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_25.addWidget(self.label_47)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem1)
        self.verticalLayout_20.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_43 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("QLabel#label_43{color:white}")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_23.addWidget(self.label_43)
        self.comboBox = QtWidgets.QComboBox(self.widget_16)
        self.comboBox.setEnabled(False)
        self.comboBox.setMinimumSize(QtCore.QSize(80, 17))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox#comboBox{color:gray}")
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_23.addWidget(self.comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem2)
        self.verticalLayout_20.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_52 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("QLabel#label_52{color:white}")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_30.addWidget(self.label_52)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget_16)
        self.lineEdit_26.setEnabled(False)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_30.addWidget(self.lineEdit_26)
        self.label_45 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("QLabel#label_45{color:white}")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_30.addWidget(self.label_45)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem3)
        self.verticalLayout_20.addLayout(self.horizontalLayout_30)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_16)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{border:1px solid gray;border-radius: 5px;color:white; }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_20.addWidget(self.pushButton_4)
        self.line_2 = QtWidgets.QFrame(self.widget_16)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_20.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel#label_2{margin-left:5px;margin-right:5px;color:white}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_20.addWidget(self.label_2)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_23 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel#label_23{color:white}")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_20.addWidget(self.label_23)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_16)
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_20.addWidget(self.lineEdit_11)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem4)
        self.verticalLayout_20.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel#label_3{color:white}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_16)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_20.addLayout(self.horizontalLayout_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_16)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{border:1px solid gray;border-radius: 5px;color:white; }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_20.addWidget(self.pushButton_3)
        self.verticalLayout_14.addWidget(self.widget_16)
        self.verticalLayout_7.addWidget(self.widget_20)
        self.widget_18 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setMaximumSize(QtCore.QSize(270, 160))
        self.widget_18.setStyleSheet("QWidget#widget_18{background-image:url(:/img/5njp9xK6q9.png)}")
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_14 = QtWidgets.QWidget(self.widget_18)
        self.widget_14.setStyleSheet("QWidget#widget_14{border: 1px solid gray;margin:5px; }")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton_9 = QtWidgets.QRadioButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_9.sizePolicy().hasHeightForWidth())
        self.radioButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setStyleSheet("QRadioButton#radioButton_9{color:white}")
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_13.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_10.sizePolicy().hasHeightForWidth())
        self.radioButton_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setStyleSheet("\n"
"QRadioButton#radioButton_10{color:white}")
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_13.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_11.sizePolicy().hasHeightForWidth())
        self.radioButton_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setStyleSheet("\n"
"QRadioButton#radioButton_11{color:white}")
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_13.addWidget(self.radioButton_11)
        self.radioButton_7 = QtWidgets.QRadioButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_7.sizePolicy().hasHeightForWidth())
        self.radioButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setStyleSheet("QRadioButton#radioButton_7{color:white}\n"
"")
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_13.addWidget(self.radioButton_7)
        self.verticalLayout_3.addWidget(self.widget_14)
        self.verticalLayout_7.addWidget(self.widget_18)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_25 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_25.sizePolicy().hasHeightForWidth())
        self.widget_25.setSizePolicy(sizePolicy)
        self.widget_25.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.widget_25.setFont(font)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(102, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{border:2px solid gray;border-radius: 10px;color:white; }")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton#pushButton_8{border:2px solid gray;border-radius: 10px;color:white;}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_8.addWidget(self.pushButton_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2 {border:2px solid gray;border-radius: 10px;color:white;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_8.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.widget_25)
        self.verticalLayout_2.addWidget(self.widget_17)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setEnabled(True)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_7)
        self.menu_3.addAction(self.action_6)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(4)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "海杂波模拟器"))
        self.label_5.setText(_translate("MainWindow", "平台信息"))
        self.label_4.setText(_translate("MainWindow", "     时    间"))
        self.pushButton_5.setText(_translate("MainWindow", "更多..."))
        self.label.setText(_translate("MainWindow", "雷达参数"))
        self.label_46.setText(_translate("MainWindow", "    载波频率"))
        self.label_47.setText(_translate("MainWindow", "GHz"))
        self.label_43.setText(_translate("MainWindow", "    极化方式"))
        self.comboBox.setItemText(0, _translate("MainWindow", "垂直极化"))
        self.comboBox.setItemText(1, _translate("MainWindow", "水平极化"))
        self.label_52.setText(_translate("MainWindow", "    入射角度"))
        self.label_45.setText(_translate("MainWindow", "°"))
        self.pushButton_4.setText(_translate("MainWindow", "更多..."))
        self.label_2.setText(_translate("MainWindow", "海洋环境参数"))
        self.label_23.setText(_translate("MainWindow", "    风    级"))
        self.label_3.setText(_translate("MainWindow", "    风    区"))
        self.pushButton_3.setText(_translate("MainWindow", "更多..."))
        self.radioButton_9.setText(_translate("MainWindow", "海浪平面"))
        self.radioButton_10.setText(_translate("MainWindow", "后向散射系数"))
        self.radioButton_11.setText(_translate("MainWindow", "多普勒及对数回波强度图"))
        self.radioButton_7.setText(_translate("MainWindow", "杂波统计分布图"))
        self.pushButton.setText(_translate("MainWindow", "运行杂波处理"))
        self.pushButton_8.setText(_translate("MainWindow", "多普勒图及\n"
"回波强度图"))
        self.pushButton_2.setText(_translate("MainWindow", "海浪模拟"))
        self.menu.setTitle(_translate("MainWindow", "参数"))
        self.menu_2.setTitle(_translate("MainWindow", "海杂波模拟"))
        self.menu_3.setTitle(_translate("MainWindow", "数据导出"))
        self.action.setText(_translate("MainWindow", "雷达模拟器参数"))
        self.action_3.setText(_translate("MainWindow", "平台状态参数"))
        self.action_5.setText(_translate("MainWindow", "海洋环境参数"))
        self.action_6.setText(_translate("MainWindow", "海杂波数据导出"))
        self.action_2.setText(_translate("MainWindow", "运行"))
        self.action_7.setText(_translate("MainWindow", "停止"))


import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
